import fs from 'node:fs';
import path from 'node:path';

// COVERAGE.md generator: enumerates the full tool surface from the registry
// so the docs can never drift from the code. Usage: npm run gen:coverage

// The registry surface is env-independent, but the account modules require
// these at import time — set fixtures BEFORE any src import.
process.env.GOOGLE_ACCOUNTS ??= 'example:user@example.com';
process.env.GOOGLE_CLIENT_ID ??= 'coverage';
process.env.GOOGLE_CLIENT_SECRET ??= 'coverage';

const { ToolRegistry } = await import('../src/registry.js');
const { SERVICES, GENERATED_GATES } = await import('../src/services.js');
const { GENERATED_SERVICES } = await import('../src/tools/generated/index.js');
const { OPTIONAL_SCOPE_BUNDLES } = await import('../src/auth.js');
type Registry = InstanceType<typeof ToolRegistry>;

const FULL_POLICY = { profile: 'full-writes' as const, readOnly: false, allow: [], deny: [] };

function makeRegistry(): Registry {
  const server = {
    registerTool: () => 'ok',
    sendToolListChanged: () => {},
    server: { setRequestHandler: () => {} },
  };
  return new ToolRegistry(server as never, FULL_POLICY);
}

const curatedOnly = makeRegistry();
for (const svc of SERVICES) svc.register(curatedOnly);
const curatedNames = new Set(curatedOnly.tools.filter((t) => !t.meta).map((t) => t.name));

const full = makeRegistry();
for (const svc of SERVICES) svc.register(full);
for (const gen of GENERATED_SERVICES) gen.register(full);

function gatingFor(service: string): string {
  if (service === 'admin') return '`GOOGLE_ADMIN_ACCOUNTS`';
  const curated = SERVICES.find((s) => s.name === service);
  if (curated?.enabled || GENERATED_GATES[service]) {
    return `scope profile bundle \`${service}\``;
  }
  return 'default';
}

// What a DEFAULT install actually registers: no optional bundles, no admin
// account, so only the ungated services. `full` above is the ceiling, reached
// only with every bundle plus an admin account.
const defaultInstall = makeRegistry();
for (const svc of SERVICES) if (!svc.enabled) svc.register(defaultInstall);
for (const gen of GENERATED_SERVICES) {
  const curated = SERVICES.find((s) => s.name === gen.name);
  if (!curated?.enabled && !GENERATED_GATES[gen.name]) gen.register(defaultInstall);
}
const defaultTools = defaultInstall.tools.filter((t) => !t.meta);
const defaultServices = [...new Set(defaultTools.map((t) => t.service))];
const unreachable = full.tools.filter((t) => !t.meta && full.isUngrantable(t));

const services = [...new Set(full.tools.filter((t) => !t.meta).map((t) => t.service))].sort();
const rows = services.map((service) => {
  const tools = full.tools.filter((t) => !t.meta && t.service === service);
  const curated = tools.filter((t) => curatedNames.has(t.name));
  return { service, tools, curated: curated.length, generated: tools.length - curated.length };
});
const totals = rows.reduce(
  (acc, r) => ({ curated: acc.curated + r.curated, generated: acc.generated + r.generated }),
  { curated: 0, generated: 0 },
);

const lines: string[] = [
  '# Coverage',
  '',
  '<!-- GENERATED by scripts/gen-coverage.ts — do not edit. Regenerate: npm run gen:coverage -->',
  '',
  `Every OAuth-reachable Google Workspace API method is a named tool: **${totals.curated} curated** (hand-written, response-shaped) + **${totals.generated} generated** (from the Google API Discovery documents) = **${totals.curated + totals.generated} tools** across **${services.length} services**, plus the \`google_api_search\`/\`google_api_call\` escape hatch for anything outside the snapshot.`,
  '',
  'All operational tools are hidden until their `{service}_discover` tool reveals them, so the idle context cost stays at the eager meta-tools only. Writes are deny-by-default via write-control regardless of tier. Generated tools whose scope is not granted return a typed `insufficient_scope` hint at call time; add the relevant bundle and re-auth to use them.',
  '',
  '## What a default install gives you',
  '',
  `That total is the **ceiling**, reached with every optional scope bundle granted plus an admin account. A default install (client id and secret, one account, no optional bundles) registers **${defaultTools.length} tools across ${defaultServices.length} services**: ${defaultServices.slice().sort().join(', ')}. Everything else in the table is one scope bundle away, and the \`Enabled by\` column says which.`,
  '',
  `**${unreachable.length} generated tools cannot succeed on any account under any configuration**, because no bundle in the catalog grants a scope they accept. They are not advertised in \`tools/list\` for that reason, though \`{service}_discover\` still lists them marked \`unreachable\` and they stay callable by name so the failure names the missing scope. Subtracting them, the reachable ceiling is **${totals.curated + totals.generated - unreachable.length} tools**.`,
  '',
  'Not covered: Alert Center (requires service-account domain-wide delegation; this server is per-user OAuth consent by design), Drive v2 (superseded by v3), Google Ads (no Discovery document; outside the generator by construction), and non-REST surfaces (Marketplace SDK, CalDAV).',
  '',
  '| Service | Curated | Generated | Total | Enabled by |',
  '|---|---:|---:|---:|---|',
  ...rows.map((r) => `| ${r.service} | ${r.curated} | ${r.generated} | ${r.tools.length} | ${gatingFor(r.service)} |`),
  `| **Total** | **${totals.curated}** | **${totals.generated}** | **${totals.curated + totals.generated}** | |`,
  '',
  `Optional scope bundles: ${Object.keys(OPTIONAL_SCOPE_BUNDLES).sort().map((b) => `\`${b}\``).join(', ')}.`,
  '',
  '## Tools by service',
  '',
];

for (const r of rows) {
  lines.push(`<details><summary><strong>${r.service}</strong> — ${r.tools.length} tools (${r.curated} curated, ${r.generated} generated)</summary>`, '', '| Tool | Tier | CUD | Description |', '|---|---|---|---|');
  for (const t of [...r.tools].sort((a, b) => a.name.localeCompare(b.name))) {
    const tier = curatedNames.has(t.name) ? 'curated' : 'generated';
    const desc = t.description.split('\n')[0].slice(0, 120).replace(/\\/g, '\\\\').replace(/\|/g, '\\|');
    lines.push(`| \`${t.name}\` | ${tier} | ${t.cud} | ${desc} |`);
  }
  lines.push('', '</details>', '');
}

fs.writeFileSync(path.join(process.cwd(), 'COVERAGE.md'), `${lines.join('\n')}`);
console.log(`COVERAGE.md: ${totals.curated + totals.generated} tools (${totals.curated} curated, ${totals.generated} generated) across ${services.length} services.`);
